# Generated by Django 4.1.3 on 2023-02-08 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('start', models.DateField(primary_key=True, serialize=False)),
                ('end', models.DateField()),
                ('transaction_completed', models.BooleanField()),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
