# Generated by Django 4.1.3 on 2023-02-09 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0007_alter_lottery_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
