# Generated by Django 4.1.3 on 2023-02-09 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0010_alter_lottery_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='winner',
        ),
        migrations.AddField(
            model_name='lottery',
            name='winner',
            field=models.ManyToManyField(blank=True, null=True, related_name='won_lotteries', to=settings.AUTH_USER_MODEL),
        ),
    ]
