# Generated by Django 4.1.3 on 2023-02-09 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0012_alter_lottery_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_lotteries', to=settings.AUTH_USER_MODEL),
        ),
    ]
