# Generated by Django 4.1.3 on 2023-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_lottery_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='transaction_completed',
            field=models.BooleanField(default=False),
        ),
    ]
